[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_port = COM14
monitor_port = COM14

board_build.arduino.memory_type = qio_qspi 
board_build.flash_mode = qio

build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=0

lib_deps = adafruit/Adafruit ADS1X15 @ ^2.5.0
           adafruit/Adafruit Unified Sensor @ ^1.1.4
           adafruit/Adafruit BMP280 Library @ ^2.1.2
           adafruit/Adafruit AHTX0 @ ^2.0.5
           bblanchon/ArduinoJson @ ^7.0.4
           tanakamasayuki/TensorFlowLite_ESP32
           knolleary/PubSubClient @ ^2.8.0
           